import Head from 'next/head'
import Image from 'next/image'
import styles from '../..//styles/Home.module.scss'
import dynamic from 'next/dynamic';
import { useState, useEffect, useRef } from 'react';
import d3 from 'd3';

import Earth from '../components/earth';





export default function Home() {
  
  return (

    <div className={styles.container}>

      <Head>
        <title>JAMVA</title>
        <meta name="disease outbreak monitoring" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.main}>
        <Earth />
      </main>

      <footer className={styles.footer}>
        Made By JAMVA!
      </footer>
    </div>
  )
}

// export async function getServerSideProps(context) {

//   const globeImage = require('../../public/images/earth-night.jpg');
//   const bg = require('../../public/images/night-sky.png');
//   return {
//     props: {
//       gi: globeImage
//   }
// };
// }
