import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import dynamic from 'next/dynamic';
import Script from 'next/script'
import { useState, useEffect, useRef } from 'react';
 
export default function Home() {
  const Globe = dynamic(import('react-globe.gl'), { ssr: false });

  return (

    <div className={styles.container}>

      <Head>
        <title>JAMVA</title>
        <meta name="disease outbreak monitoring" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      <main className={styles.main}>
        <Globe />
      </main>

      <footer className={styles.footer}>
        Made By JAMVA!
      </footer>
    </div>
  )
}
